[package]
name = "short_url_web"
version = "0.1.0"
authors = ["ryota-sakamoto <sakamo.ryota+github@gmail.com>"]

[dependencies]
actix-web = "1.0"
env_logger = "0.6.2"
mysql = "14.0.0"
futures = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rand = "0.5"
rust-crypto = "0.2"